#!/bin/bash

phase=$(head -n 1 .phase 2> /dev/null)
if [ -z $phase ]; then
    exit 1
fi
echo "PHASE:"$phase


if [ $phase = "dev" ]; then    	
	docker-compose -p=blue -f env/docker-compose.yml $@
	exit 0
fi

if [ $phase = "prd" ]; then 
    acvite=$(sh tools/whoisactive.sh)  
    if [ -z "$acvite" ]; then
		acvite='blue'
	fi
	docker-compose -p=${acvite} -f env/docker-compose.${acvite}.yml $@
	exit 0
	
fi

docker-compose $@