#!/bin/sh

phase=$(sh tools/get_phase.sh)
echo "PHASE:"$phase


if [ $phase = "dev" ]; then    	
	docker-compose -p=dev -f env/docker-compose.yml $@
	exit 0
fi

if [ $phase = "uat" ]; then    		
	docker-compose -p=uat -f env/docker-compose.uat.yml $@
	exit 0
fi

if [ $phase = "prd" ]; then 
    acvite=$(sh tools/whoisactive.sh)  
    if [ -z "$acvite" ]; then
		acvite='blue'
	fi
	docker-compose -p=${acvite} -f env/docker-compose.${acvite}.yml $@
	exit 0
	
fi

docker-compose $@