#!/bin/bash

phase=$(head -n 1 .phase 2> /dev/null)
if [ -z $phase ]; then
    exit 1
fi
echo "PHASE:"$phase


if [ $phase = "prd" ]; then 
	docker-compose -p=prd -f env/docker-compose.env.yml down
	docker-compose -p=prd -f env/docker-compose.env.yml build
	docker-compose -p=prd -f env/docker-compose.env.yml up -d --remove-orphans
	docker-compose -p=green -f env/docker-compose.green.yml down
	docker-compose -p=blue -f env/docker-compose.blue.yml down
fi

./dcompose down
./dcompose build
./dcompose up -d --remove-orphans
./state
