#!/bin/bash

in_phase=$(echo "$1" | tr '[:upper:]' '[:lower:]')

if [[ $in_phase = "prd" ]] || [[ $in_phase = "dev" ]]; then    
	echo $in_phase > .phase
else	
    echo "Input not valid! Please use: ${0##*/} {dev|prd}"
fi

