#!/bin/bash

#!/bin/bash

phase=$1

if [[ -z $1 ]]; then
    phase=$(head -n 1 .phase 2> /dev/null)
    if [[ -z $phase ]]; then
    	phase='dev'
    fi
fi

echo "Dummy test..."
echo "PHASE:"$phase

if [ $phase == "dev" ]; then
curl -I 127.0.0.1:8080
fi

if [ $phase == "uat" ]; then
curl -I http://127.0.0.1:3000
fi

if [ $phase == "prd" ]; then
curl -I http://127.0.0.1
fi