#!/bin/bash


if [[ -z $1 ]]; then
   phase=$(head -n 1 .phase 2> /dev/null)
fi

echo "Dummy test..."
echo "PHASE:"$phase

if [ $phase == "dev" ]; then
curl -I http://127.0.0.1:8080
fi


if [ $phase == "prd" ]; then
curl -I http://127.0.0.1
fi