version: '3.0'
services:
  mysql:
    build: ./docker-file/mysql
    volumes:
      - "./storage/mysql:/var/lib/mysql"                         
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      dev:
        ipv4_address: 10.0.0.2
    ports:
      - "3306:3306" 
      - "33060:33060"
      - "33062:33062"
      
  flask:
    build: ./docker-file/flask
    links:
      - mysql
    volumes:
      - ./app/server:/home/web
      - ./storage/fs:/data/fs
    environment:
      FLASK_ENV: dev
    networks:
      dev:
        ipv4_address: 10.0.0.3

  nginx:
    build: ./docker-file/nginx
    links:
      - flask
    volumes:
      - "./log/nginx:/var/log/nginx"
      - "./app/web:/usr/share/nginx/html"
      - "./cert:/etc/nginx/cert"
    ports:
      - "8080:80"
      - "8083:443"
    restart: always
    networks:
      dev:
        ipv4_address: 10.0.0.4

networks:
  dev:
    ipam:
      config:
        - subnet: 10.0.0.1/16