version: '3.0'
services:
  mongo:
    build: ./docker-file/mongo
    volumes:
      - "./storage/mongodb:/data/db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      dev:
        ipv4_address: 10.0.0.2
    ports:
      - "27017:27017"
  flask:
    build: ./docker-file/flask
    links:
      - mongo
    volumes:
      - ./app/server:/home/web
      - ./storage/fs:/data/fs
    environment:
      ENV: dev
    networks:
      dev:
        ipv4_address: 10.0.0.3

  nginx:
    build: ./docker-file/nginx
    links:
      - flask
    volumes:
      - "./log/nginx:/var/log/nginx"
      - "./app/web:/usr/share/nginx/html"
    ports:
      - "8080:80"
    restart: always
    networks:
      dev:
        ipv4_address: 10.0.0.4

networks:
  dev:
    ipam:
      config:
        - subnet: 10.0.0.1/16