version: '3.0'
services:
  
  mysql:
    build: ./docker-file/mysql
    volumes:
      - "./storage/mysql:/var/lib/mysql"
      - "./log/mysql:/var/log/mysql"      
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456       
    ports:
      - "3306:3306" 

  flask:
    build: ./docker-file/flask
    links:
      - mysql
    volumes:
      - ./app/server:/home/web      
      - ./log/flask:/var/log/flask
      - ./storage/fs:/data/fs
    environment:
      FLASK_ENV: dev

  nginx:
    build: ./docker-file/nginx
    links:
      - flask
    volumes:
      - "./log/nginx:/var/log/nginx"
      - "./app/web:/usr/share/nginx/html"
      - "./cert:/etc/nginx/cert"      
    ports:
      - "8080:80"
    restart: always

