version: '3.0'
services:
     
  mysql:
    build: ./docker-file/mysql
    volumes:
      - "../storage/mysql:/var/lib/mysql"      
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$') 
      interval: 3s      
      retries: 5  
    networks:
      - webgateway 
    ports:
      - "3303:3306" 

  flask:
    build: ./docker-file/flask
    volumes:
      - ./white/server:/home/web      
      - ./white/log/flask:/var/log/flask
      - ../storage/fs:/data/fs
    environment:
      FLASK_ENV: uat
      FLASK_DEBUG: 0            
      GUN_WORKERS: 2     
    networks:
      - webgateway
    depends_on:
      - mysql


  nginx:
    build: ./docker-file/nginx
    labels:  
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.backend.healthcheck.path=/health"
      - "traefik.backend.healthcheck.interval=5s"
      - "traefik.http.middlewares.test-retry.retry.attempts=5"
      - "traefik.frontend.rule=Method:CONNECT,DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT,TRACE"
      - "traefik.port=8000"
    volumes:      
      - "./white/web:/var/www:ro"      
    restart: always     
    networks:
      - webgateway 
    depends_on:
      - flask         

  proxy:
    image: traefik:v1.7
    networks:
        - webgateway
    ports:
        - "3000:80"
        - "3030:8080"
        - "3443:443"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik.uat.toml:/traefik.toml:ro
    networks:
      - webgateway 


networks:
    webgateway:
        driver: bridge  


    