version: '3.0'
services:
     
  flask:
    build: ./docker-file/flask    
    volumes:
      - ./white/server:/home/web      
      - ./white/log/flask:/var/log/flask
      - ../storage/fs:/data/fs
    environment:
      FLASK_ENV: dev      
      FLASK_DEBUG: 1
      GUN_WORKERS: 2      
    ports:
      - "5050:5000"  


  nginx:
    build: ./docker-file/nginx
    volumes:
      - "./white/log/nginx:/var/log/nginx"
      - "./white/web:/usr/share/nginx/html:ro"      
    restart: always
    ports:
      - "8000:8000"    


  mysql:
    build: ./docker-file/mysql
    volumes:
      - "../storage/mysql:/var/lib/mysql"      
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$') 
      interval: 3s      
      retries: 5       
    ports:
      - "3306:3306"   

