version: '3.0'
services:
  
  mysql:    
    ports:
      - "3306:3306" 

  flask:
    environment:
      FLASK_ENV: dev      
      FLASK_DEBUG: 1
      GUN_WORKERS: 2      
    ports:
      - "5050:5000"       
  
  nginx:    
    ports:
      - "8080:80"    

