version: '3.0'
services:
     
  flask:
    build: ./docker-file/flask
    volumes:
      - ./blue/server:/home/web      
      - ./blue/log/flask:/var/log/flask
      - ../storage/fs:/data/fs
    environment:
      FLASK_ENV: prd            
      GUN_WORKERS: 4     
    networks:
      - env


  nginx:
    build: ./docker-file/nginx
    labels:  
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.backend.healthcheck.path=/health"
      - "traefik.backend.healthcheck.interval=5s"
      - "traefik.http.middlewares.test-retry.retry.attempts=5"
      - "traefik.frontend.rule=Method:CONNECT,DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT,TRACE"
      - "traefik.port=8000"
    volumes:      
      - "./blue/web:/usr/share/nginx/html:ro"      
    restart: always     
    depends_on:
      - flask 
    networks:
      - env          

networks:
    env:
        external:
            name: prd_webgateway              

    